## Read The Train and Test Dataset

In [12]:
import numpy as np
import pandas as pd
data = pd.read_csv('C:/Users/Shankeerthan/Desktop/Data-Storm 1.0/credit_card_default_train.csv')
test = pd.read_csv('C:/Users/Shankeerthan/Desktop/Data-Storm 1.0/credit_card_default_test.csv')

## Describe The Train Dataset

In [14]:
data.describe()

,PAY_JULY,PAY_AUG,PAY_SEP,PAY_OCT,PAY_NOV,PAY_DEC,DUE_AMT_JULY,DUE_AMT_AUG,DUE_AMT_SEP,DUE_AMT_OCT,DUE_AMT_NOV,DUE_AMT_DEC,PAID_AMT_JULY,PAID_AMT_AUG,PAID_AMT_SEP,PAID_AMT_OCT,PAID_AMT_NOV,PAID_AMT_DEC,NEXT_MONTH_DEFAULT
count,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,2.400000e+04,2.400000e+04,2.400000e+04,2.400000e+04,2.400000e+04,2.400000e+04,2.400000e+04,2.400000e+04,2.400000e+04,2.400000e+04,24000.000000,2.400000e+04,24000.000000
mean,-0.014208,-0.130042,-0.158667,-0.215542,-0.261167,-0.287667,1.188697e+05,1.140727e+05,1.092435e+05,1.003573e+05,9.377699e+04,9.034068e+04,1.330648e+04,1.386675e+04,1.209312e+04,1.122527e+04,11174.737208,1.230122e+04,0.222083
std,1.124897,1.200566,1.198875,1.166608,1.131855,1.147847,1.710424e+05,1.652414e+05,1.614737e+05,1.490071e+05,1.417389e+05,1.387237e+05,3.935742e+04,5.648588e+04,4.065924e+04,3.624693e+04,36040.821759,4.233848e+04,0.415656
min,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-3.824900e+05,-1.611850e+05,-1.420790e+05,-3.927000e+05,-1.878820e+05,-7.844830e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,8.246250e+03,6.968750e+03,6.238500e+03,5.429000e+03,4.179750e+03,2.913000e+03,2.310000e+03,1.956000e+03,9.010000e+02,6.930000e+02,610.000000,3.070000e+02,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.156850e+04,4.871700e+04,4.641150e+04,4.410500e+04,4.186300e+04,3.940900e+04,4.920000e+03,4.646500e+03,4.197000e+03,3.465000e+03,3465.000000,3.465000e+03,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.562745e+05,1.489050e+05,1.401622e+05,1.269750e+05,1.169262e+05,1.144352e+05,1.160500e+04,1.155000e+04,1.062600e+04,9.360000e+03,9411.500000,9.252500e+03,0.000000
max,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,2.228020e+06,2.272881e+06,3.844046e+06,2.059564e+06,2.141765e+06,2.221444e+06,2.017905e+06,3.890638e+06,2.069852e+06,1.434510e+06,965557.000000,1.221218e+06,1.000000

## Data Preprocessing

In [2]:
def New_Balance_Limit_V1(x):
    if (x[-1]=="M"):
        x=float(x[:len(x)-1])*1000000
    elif(x[-1]=="K"):
        x=float(x[:len(x)-1])*1000
    else:
        x=float(x)
    return(x)

data["New_Balance_Limit_V1"] = data["Balance_Limit_V1"].apply(New_Balance_Limit_V1)
data.drop("Balance_Limit_V1",axis=1,inplace=True)
data.rename(columns={"New_Balance_Limit_V1" : "Balance_Limit_V1"},inplace=True)
col=list(data.columns)
last=col.pop()
col.insert(1,last)
data=data[col]

test["New_Balance_Limit_V1"] = test["Balance_Limit_V1"].apply(New_Balance_Limit_V1)
test.drop("Balance_Limit_V1",axis=1,inplace=True)
test.rename(columns={"New_Balance_Limit_V1" : "Balance_Limit_V1"},inplace=True)
col1=list(test.columns)
last1=col1.pop()
col1.insert(1,last1)
test=test[col1]

Change_values = {'Gender':{'M':1, 'F':0},
                'EDUCATION_STATUS':{'Graduate':2,'High School':1,'Other':0},
                'MARITAL_STATUS':{'Single':1,'Married':2,'Other':3},
                'AGE':{'Less than 30':0,'31-45':1,'46-65':2,'More than 65':3}}

data.replace(Change_values, inplace=True)
test.replace(Change_values, inplace=True)

index=data.pop('Client_ID')
label=data.pop('NEXT_MONTH_DEFAULT')
index1=test.pop('Client_ID')

## Plot The Correlation Matrix

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

corrmat = data.corr()
top_corr_features = corrmat.index
plt.figure(figsize=(20,20))

corrmatgraph=sns.heatmap(data[top_corr_features].corr(),annot=True,cmap="RdYlGn")
figure = corrmatgraph.get_figure()    
figure.savefig('data_corr.png', dpi=400)

## Train / Validation Split

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

train_data, test_data, train_label, test_label = train_test_split( data, label, test_size = 0.4,random_state=100)

## Feature Scaling

In [6]:
from sklearn import preprocessing

features = train_data.iloc[:,[0,11,12,13,14,15,16,17,18,19,20,21,22]].values
features1 = test_data.iloc[:,[0,11,12,13,14,15,16,17,18,19,20,21,22]].values
standardscalar = preprocessing.StandardScaler()
train_data1= standardscalar.fit_transform(features) 
train_data = np.concatenate((train_data1,train_data.iloc[:,[1,2,3,4,5,6,7,8,9,10]].values),axis=1)
test_data1 = standardscalar.transform(features1) 
test_data = np.concatenate((test_data1,test_data.iloc[:,[1,2,3,4,5,6,7,8,9,10]].values),axis=1)

features2 = test.iloc[:,[0,11,12,13,14,15,16,17,18,19,20,21,22]].values
test1 = standardscalar.fit_transform(features2) 
test = np.concatenate((test1,test.iloc[:,[1,2,3,4,5,6,7,8,9,10]].values),axis=1)

## Build The Xgboost Model

In [15]:
import xgboost
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

classifier = xgboost.XGBClassifier()

classifier.fit( train_data, train_label )
predict_label = classifier.predict( test_data )

print(classification_report(test_label,predict_label)) 
print ("AUC Score (Test): %f" % metrics.roc_auc_score(test_label, predict_label))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7525
           1       0.67      0.36      0.47      2075

    accuracy                           0.82      9600
   macro avg       0.76      0.66      0.68      9600
weighted avg       0.81      0.82      0.80      9600

AUC Score (Test): 0.656711

## Save Predictions as csv File

In [8]:
submit = pd.read_csv('C:/Users/Shankeerthan/Desktop/Data-Storm 1.0/day 1/submission 12/submit1.csv')
predic=classifier.predict(test)
Next_month=pd.DataFrame(predic,columns=['NEXT_MONTH_DEFAULT'])
submit=pd.concat([submit,Next_month],axis=1)
export_csv=submit.to_csv('C:/Users/Shankeerthan/Desktop/Data-Storm 1.0/day 1/submission 12/submit1.csv',index=None)